- name: Remove jenkins container
  hosts: all

  tasks:
    - name: Uninstall Jenkins
      block:
        - name: Remove jenkins container
          docker_container:
            name: jenkins
            state: absent
        - name: Delete jenkins volumes
          docker_volume:
            name: '{{ item }}'
            state: absent
          with_items:
            - jenkins-docker-certs
            - jenkins-data
        - name: Delete initial image
          docker_image:
            name: jenkins/jenkins
            tag: lts
            state: absent
